import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Navbar from "../components/Navbar";
import bodyImage from "../public/assets/hero.svg";
import Message from "../components/Message";
export default function Home() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <Navbar />
        <body className={styles["hero"]}>
          <section className={styles["text"]}>
            <h3>
              healthy <span className={styles["colorGreen"]}>Diet</span>
            </h3>
            <h3>
              healthy <span className={styles["colorRed"]}>Body</span>
            </h3>
            <h3>
              healthy <span className={styles["colorYellow"]}>Life</span>
            </h3>
          </section>
          <section className={styles["image__container"]}>
            <img src={bodyImage.src} alt="hero" />
          </section>
        </body>
        <Message />
      </main>
    </>
  );
}
